// Mocks generated by Mockito 5.2.0 from annotations
// in my_favorite_games/test/app/modules/search/domain/usecases/search_games_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:my_favorite_games/app/core/error/failure/failure.dart' as _i5;
import 'package:my_favorite_games/app/core/shared/entities/game.dart' as _i6;
import 'package:my_favorite_games/app/modules/search/domain/repositories/search_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [SearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepository extends _i1.Mock implements _i3.SearchRepository {
  MockSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Game>>> searchGames(
          String? searchTerm) =>
      (super.noSuchMethod(Invocation.method(#searchGames, [searchTerm]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Game>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.Game>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.Game>>>);
}
