// Mocks generated by Mockito 5.2.0 from annotations
// in my_favorite_games/test/app/modules/search/data/repositories/search_repository_implementation_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i3;
import 'package:internet_connection_checker/internet_connection_checker.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:my_favorite_games/app/core/network/network_info_implementation.dart'
    as _i4;
import 'package:my_favorite_games/app/core/shared/models/game_model.dart'
    as _i7;
import 'package:my_favorite_games/app/modules/search/data/datasources/search_data_source_implementation.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeInternetConnectionChecker_0 extends _i1.Fake
    implements _i2.InternetConnectionChecker {}

class _FakeDio_1 extends _i1.Fake implements _i3.Dio {}

/// A class which mocks [NetworkInfoImplementation].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfoImplementation extends _i1.Mock
    implements _i4.NetworkInfoImplementation {
  MockNetworkInfoImplementation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InternetConnectionChecker get internetConnectionChecker =>
      (super.noSuchMethod(Invocation.getter(#internetConnectionChecker),
              returnValue: _FakeInternetConnectionChecker_0())
          as _i2.InternetConnectionChecker);
  @override
  _i5.Future<bool> get hasInternetConnection =>
      (super.noSuchMethod(Invocation.getter(#hasInternetConnection),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
}

/// A class which mocks [SearchDataSourceImplementation].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchDataSourceImplementation extends _i1.Mock
    implements _i6.SearchDataSourceImplementation {
  MockSearchDataSourceImplementation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Dio get client =>
      (super.noSuchMethod(Invocation.getter(#client), returnValue: _FakeDio_1())
          as _i3.Dio);
  @override
  _i5.Future<List<_i7.GameModel>> search({String? searchTerm}) =>
      (super.noSuchMethod(
              Invocation.method(#search, [], {#searchTerm: searchTerm}),
              returnValue: Future<List<_i7.GameModel>>.value(<_i7.GameModel>[]))
          as _i5.Future<List<_i7.GameModel>>);
}
